apiVersion: v1
kind: Service
metadata:
  name: service-db
spec:
  type: ClusterIP # only accept internal(cluster) requests
  ports:
    - port: 3306
  selector:
    name: mysql # name used in the labels field inside statefulset.yaml file
